apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: ek8sv1
  labels:
    app: redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31012
  selector:
    app: redis #选择 pod label