#sudo: required

language: go

services:
  - docker

os:
  - linux
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
install:
  true
script:
  # all
  - go test ./...

  # 查看环境变量
  - pwd; PRODIR=$(pwd);echo $PRODIR;
  - echo $HOME; echo $PATH; which go;   
  
  # eModule
  - cd $PRODIR/eModule; go run .

  # ubuntu
  - cd $PRODIR/cicd/docker; chmod +x ./build.sh; ./build.sh 

  # eDocker
  # 如果 sudo ./build.sh 有问题,PATH 和当前用户不一致没有 go. 
  - cd $PRODIR/eDocker/docker; chmod +x ./build.sh; ./build.sh 
  
  # eYaml
  - cd $PRODIR/eYaml/docker; chmod +x ./build.sh; ./build.sh 