#sudo: required

language: go

services:
  - docker

os:
  - linux
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
install:
script:
  # all
  - go test ./...

  - echo "\n***********************";
  - pwd; PRODIR=$(pwd);echo $PRODIR;

  # eDocker
  - pwd; echo $PATH; which go # 查看环境变量
  - cd $PRODIR/example/eDocker/docker; chmod +x ./build.sh; ./build.sh # 如果 sudo ./build.sh 有问题,PATH 和当前用户不一致没有 go. 
  
  # eYaml
  - pwd; echo $PATH;
  - cd $PRODIR/example/eYaml/docker; chmod +x ./build.sh; ./build.sh 