#sudo: required

language: go

services:
  - docker

os:
  - linux
go:
  - 1.13.x
env:
  - GO111MODULE=on
install:
  true

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin

script:
  - chmod +x ./build/build.sh;./build/build.sh
  
  - chmod +x ./test/test.sh;./test/test.sh

after_success:
  - golangci-lint run 