#sudo: required

language: go

services:
  - docker

os:
  - linux
go:
  - 1.14.x
env:
  - GO111MODULE=on
install:
  true

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - cd build;make
after_success:
  - golangci-lint run 