#sudo: required

language: go

services:
  - docker
  - mysql
  - redis
os:
  - linux
go:
  - 1.14.x
env:
  global:
    - GO111MODULE=on
    - CI_ENV="travis"
    - CI_ENV_NO_DOCKER="yes"

install:
  true

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin
script:
  - pwd; ls -a -l
  # docker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  # mysql
  - chmod +x tool/test/init_mysql.sh; tool/test/init_mysql.sh
  # app
  - cd build; make
after_success:
  - golangci-lint run 