#sudo: required

language: go

services:
  - docker

os:
  - linux
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
install:
script:
  - go test ./...
  - cd example/eDocker/docker; 
  - chmod +x ./build.sh
  - sudo ./build.sh