apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix:  prod-
commonLabels:
    variant:  prod
commonAnnotations:
    note: Hello, I am  prod!
bases:
- ../../base

resources:
- client/client-deploy.yaml
- client/client-svc.yaml

configMapGenerator:
- name: cm-user
  files:
  - configs/app.yaml
  - configs/grpc.yaml
  - configs/http.yaml
  - configs/mysql.yaml
  - configs/redis.yaml

patchesStrategicMerge:
  - deploy-path/user-deploy.yaml

