apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  labels:
    app: client # istio
    version: v1 # istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: client #标注 pod label
        version: v1
    spec:
      containers:
      - name: client
        image: dockerxpub/clienttest:v1.5.5
        imagePullPolicy: IfNotPresent
        command: ["bash", "/script/test.sh","0.001","v1","1","$(USER_SVC)"]
