apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: goms
  labels:
    svc: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #选择 pod label
  template:
    metadata:
      labels:
        app: mysql #标注 pod label
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"