apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: goms
  labels:
    app: redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30002
  selector:
    app: redis