apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  namespace: goms
  labels:
    app: redis
spec:
  serviceName: redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 150m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 400Mi
          ports:
            - containerPort: 6379