apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: goms
  labels:
    svc: user-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user  #选择 pod label
  template:
    metadata:
      labels:
        app: user #标注 pod label
    spec:
      containers:
      - name: user
        image: goms-eredis:latest
        imagePullPolicy: IfNotPresent
        # args:
        # - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_SVC_ADDR 
          value: 'redis-svc:6379'
        - name: MYSQL_SVC_DSN
          value: "root:mysql@tcp(mysql-svc:3306)/dbtest?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
        - name: MYSQL_SERVICE_HOST
          value: 'mysql-svc'
        - name: MYSQL_SERVICE_PORT
          value: '3306'
        - name: MYSQL_USERNAME 
          value: 'root'
        - name: MYSQL_PASSWORD
          value: 'mysql'