apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: ek8sv3
  labels:
    svc: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31021
  selector:
    app: mysql #选择 pod label