kind: Kustomization
commonAnnotations:
    note: goms-base-debug
bases:
- ../base
resources:
- secret/mysql.yaml
- secret/redis.yaml
- mysql-pv/pv-local.yaml
- redis-pv/pv-local.yaml
- initdbd/initdbd-deploy.yaml

configMapGenerator:
- name: cm-user
  files:
  - user-cm/configs/app.yaml
  - user-cm/configs/grpc.yaml
  - user-cm/configs/http.yaml
  - user-cm/configs/mysql.yaml
  - user-cm/configs/redis.yaml

patchesStrategicMerge:
  - initdbd/mysql-sts-patch.yaml

vars:
- name: USER_SVC
  objref:
    kind: Service
    name: user-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: MYSQL_SVC
  objref:
    kind: Service
    name: mysql-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: REDIS_SVC
  objref:
    kind: Service
    name: redis-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
