kind: Kustomization
commonAnnotations:
    note: goms-base-debug
bases:
- ../base
resources:
- mysql-pv/pv-local.yaml
- redis-pv/pv-local.yaml
- mysql-initdbd/initdbd-deploy.yaml

configMapGenerator:
- name: cm-user
  files:
  - user-cm/configs/app.yaml
  - user-cm/configs/grpc.yaml
  - user-cm/configs/http.yaml
  - user-cm/configs/mysql.yaml
  - user-cm/configs/redis.yaml

vars:
- name: MYSQL-SVC
  objref:
    kind: Service
    name: mysql-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: REDIS-SVC
  objref:
    kind: Service
    name: redis-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
