apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
    service: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis #选择 pod label

