apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  # type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    # nodePort: 32023
  selector:
    app: user #选择 pod label

