apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user #选择 pod label

