apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    service: mysql
spec:
  ports:
  - port: 3306
    name: tcp # istio 规范
    protocol: TCP
    targetPort: 3306
  clusterIP: None # headless 服务
  selector:
    app: mysql #选择 pod label
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  labels:
    app: mysql # istio 规范
    version: v1 # istio 规范
spec:
  serviceName: mysql-svc # bound Service
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: mysql #标注 pod label
        version: v1
    spec:
      containers:
      - name: mysql
        image: dockerxpub/mysqltest:v2.2.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 3306
        # env:
        # - name: MYSQL_ALLOW_EMPTY_PASSWORD 
        #   value: "yes"
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumeClaimTemplates:   # 看作pvc模板
  - metadata:
      name: mysql-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "mysql-pv-local" # bound pv
      resources:
        requests:
          storage: 5Gi
