apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    service: mysql
spec:
  ports:
  - port: 3306
    name: tcp # istio
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql #选择 pod label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql # istio
    version: v1 # istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: mysql #标注 pod label
        version: v1
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: Always
        env:
        - name: MYSQL_DATABASE
          value: test_db
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
