apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    service: mysql
spec:
  ports:
  - port: 3306
    name: tcp # istio
    protocol: TCP
    targetPort: 3306
  clusterIP: None # headless 服务
  selector:
    app: mysql # 选择 pod label
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  labels:
    app: mysql # istio
    version: v1 # istio
spec:
  serviceName: mysql-svc # sts, bound service
  replicas: 1
  selector:
    matchLabels:
      app: mysql  # 选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: mysql # 标注 pod label
        version: v1
    spec:
      containers:
      - name: mysql
        image: dockerxpub/mysqltest:v2.2.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumeClaimTemplates:   # 看作 pvc 模板
  - metadata:
      name: mysql-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: mysql-pv-class # bound pv
      resources:
        requests:
          storage: 5Gi
