apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    service: mysql
spec:
  ports:
  - port: 3306
    name: tcp # istio 规范
    protocol: TCP
    targetPort: 3306
  # clusterIP: None
  selector:
    app: mysql #选择 pod label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql # istio 规范
    version: v1 # istio 规范
spec:
  # serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: mysql #标注 pod label
        version: v1
    spec:
      containers:
      - name: mysql
        image: dockerxpub/mysqltest:v2.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        # env:
        # - name: MYSQL_ALLOW_EMPTY_PASSWORD 
        #   value: "yes"
      #   volumeMounts:
      #   - name: mysql-vol
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-vol
      #   hostPath:
      #     path: /var/lib/mysqlx/vol #宿主机路径
      #     type: Directory
