apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: ek8sv2
  labels:
    svc: redis-svc
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 31022
  selector:
    app: redis #选择 pod label