apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  labels:
    app: mysql
    version: v1
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: mysql #标注 pod label
        version: v1
    spec:
      containers:
      - name: mysql
        image: dockerxpub/goms-mysqltest:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD 
          value: "yes"
  volumeClaimTemplates:   #看作pvc模板
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      #   volumeMounts:
      #   - name: mysql-vol
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-vol
      #   hostPath:
      #     path: /var/lib/mysqlx/vol #宿主机路径
      #     type: Directory

