apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    app: redis
    version: v1
spec:
  serviceName: redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: redis  #选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: redis #标注 pod label
        version: v1
    spec:
      containers:
      - name: redis
        image: dockerxpub/goms-redistest:v1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
  volumeClaimTemplates:   #看作pvc模板
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

