# mysql
addr: "{MYSQL_SERVICE_HOST}:{MYSQL_SERVICE_PORT}"
dsn: "{MYSQL_USERNAME}:{MYSQL_PASSWORD}@tcp({MYSQL_SERVICE_HOST}:{MYSQL_SERVICE_PORT})/dbtest?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
# dsn: "{MYSQL_USERNAME}:{MYSQL_PASSWORD}@/{MYSQL_DATABASE}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
# dsn: "{user}:{password}@tcp(127.0.0.1:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"