# apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
    note: goms-dev
bases:
- ../../base

resources:
- secret/mysql.yaml
- secret/redis.yaml
- pv/pv-local.yaml
- client/client-deploy.yaml
- user/user-deploy-v2.yaml
- initdbd/initdbd-deploy.yaml

configMapGenerator:
- name: cm-user
  files:
  - configs/app.yaml
  - configs/grpc.yaml
  - configs/http.yaml
  - configs/mysql.yaml
  - configs/redis.yaml

patchesStrategicMerge:
  - user/user-deploy-v1-patch.yaml

vars:
- name: USER_SVC
  objref:
    kind: Service
    name: user-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: MYSQL_SVC
  objref:
    kind: Service
    name: mysql-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: REDIS_SVC
  objref:
    kind: Service
    name: redis-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
