# apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
    note: goms-dev
bases:
- ../../base

resources:
- pv/pv-local.yaml
- client/client-deploy.yaml
- other/user-deploy-v2.yaml

configMapGenerator:
- name: cm-user
  files:
  - configs/app.yaml
  - configs/grpc.yaml
  - configs/http.yaml
  - configs/mysql.yaml
  - configs/redis.yaml

patchesStrategicMerge:
  - patch/user-deploy-v1-patch.yaml
