# apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
    note: goms-dev
bases:
- ../../base

resources:
- pv/pv-local.yaml
- client/client-deploy.yaml
- other/user-deploy-v2.yaml
- mysql-initdbd/initdbd-deploy.yaml

configMapGenerator:
- name: cm-user
  files:
  - configs/app.yaml
  - configs/grpc.yaml
  - configs/http.yaml
  - configs/mysql.yaml
  - configs/redis.yaml

patchesStrategicMerge:
  - patch/user-deploy-v1-patch.yaml

vars:
- name: MYSQL-SVC
  objref:
    kind: Service
    name: mysql-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: REDIS-SVC
  objref:
    kind: Service
    name: redis-svc
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
