apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
    service: redis
spec:
  ports:
  - port: 6379
    name: redis # istio
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis # 选择 pod label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sts
  labels:
    app: redis # istio
    version: v1 # istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis  # 选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: redis # 标注 pod label
        version: v1
    spec:
      containers:
      - name: redis
        image: redis:6.0
        imagePullPolicy: IfNotPresent
        command: ["redis-server","--requirepass","pwtest"]
        ports:
        - containerPort: 6379
