apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
    service: redis
spec:
  ports:
  - port: 6379
    name: redis # istio
    protocol: TCP
    targetPort: 6379
  clusterIP: None # headless service
  selector:
    app: redis # 选择 pod label
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    app: redis # istio
    version: v1 # istio
spec:
  serviceName: redis-svc # sts, bound service
  replicas: 1
  selector:
    matchLabels:
      app: redis  # 选择 pod label
      version: v1
  template:
    metadata:
      labels:
        app: redis # 标注 pod label
        version: v1
    spec:
      containers:
      - name: redis
        image: redis:6.0
        imagePullPolicy: IfNotPresent
        command: ["redis-server","--requirepass","$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-pv
          mountPath: /var/lib/redis
  volumeClaimTemplates: # 看作 pvc 模板
  - metadata:
      name: redis-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: redis-pv-class # bound pv
      resources:
        requests:
          storage: 5Gi
