name: make_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tool:
    name: tool
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: mock
      env:
        CHUB: ${{ 'docker.io' }}
        CHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        CHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GOMS_NAME_SPACE: ${{ secrets.DOCKER_USERNAME }}
      working-directory: ./tests/mock/build
      run: |
        docker login -u $CHUB_USERNAME -p $CHUB_PASSWORD $CHUB
        make docker
        make push

  test:
    name: test
    env:
      CI_ENV_DOCKER: no
    runs-on: ubuntu-latest

    services:
      mysql:
        image: dockerxpub/goms-mysqltest:v2.2.1
        ports:
          - 3306:3306
      redis:
        image: dockerxpub/goms-redistest:v1.4.2
        ports:
          - 6379:6379

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Unit test
      working-directory: ./tests/unit
      run: |
        bash ./run.sh

    - name: Integration test
      working-directory: ./tests/integration
      run: |
        source ./install.sh
        bash ./run.sh
        cat ./test.log

  build:
    name: build
    runs-on: ubuntu-latest


    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: build
      env:
        CHUB: ${{ 'docker.io' }}
        CHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        CHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GOMS_NAME_SPACE: ${{ secrets.DOCKER_USERNAME }}
      working-directory: ./build
      run: |
        docker login -u $CHUB_USERNAME -p $CHUB_PASSWORD $CHUB
        chmod +x ./build.sh && ./build.sh