name: make_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: dockerxpub/goms-mysqltest:v2.2.1
        ports:
          - 3306:3306
      redis:
        image: dockerxpub/goms-redistest:v1.4.2
        ports:
          - 6379:6379

    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Print env
      run: |
        echo $PATH
        echo $HOME
        pwd
        ls -a -l ./
        docker ps
        docker ps | grep mysql | awk '{ print $1 }' | xargs docker logs

    - name: Make test
      env:
        CI_ENV_DOCKER: no
      run: |
        cd build
        make test
    - name: Integration test
      run: |
        cd tests/integration
        source ./install.sh
        bash ./run.sh
    - name: Make compile
      run: |
        cd build
        make compile

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Print env
      run: |
        echo $PATH
        echo $HOME
        pwd
        ls -a -l ./

    - name: Make compile
      run: |
        cd build
        make compile

    - name: Make docker push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GOMS_NAME_SPACE: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        cd build
        make docker push

    - name: Make clean
      run: |
        cd build
        make clean
